create table if not exists public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'admin' check (role in ('admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.course_categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  icon text,
  color text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  category_id bigint references public.course_categories(id) on delete set null,
  title text not null,
  alternate_title text,
  slug text not null unique,
  description text,
  instructor text,
  image_url text,
  cover_url text,
  is_featured boolean not null default false,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  title text not null,
  youtube_url text not null,
  youtube_video_id text not null,
  image_url text,
  description text,
  sort_order integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists courses_catalog_idx on public.courses (is_published, is_featured, updated_at desc);
create index if not exists courses_category_idx on public.courses (category_id, is_published);
create index if not exists lessons_course_order_idx on public.lessons (course_id, sort_order);
create index if not exists lessons_visibility_idx on public.lessons (course_id, is_published);

alter table public.admin_profiles enable row level security;
alter table public.course_categories enable row level security;
alter table public.courses enable row level security;
alter table public.lessons enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.admin_profiles where user_id = auth.uid() and role = 'admin');
$$;

create policy "public can read active categories" on public.course_categories for select using (is_active = true or public.is_admin());
create policy "public can read published courses" on public.courses for select using (is_published = true or public.is_admin());
create policy "public can read published lessons" on public.lessons for select using (is_published = true or public.is_admin());
create policy "admins manage admin profiles" on public.admin_profiles for all using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());
create policy "admins manage categories" on public.course_categories for all using (public.is_admin()) with check (public.is_admin());
create policy "admins manage courses" on public.courses for all using (public.is_admin()) with check (public.is_admin());
create policy "admins manage lessons" on public.lessons for all using (public.is_admin()) with check (public.is_admin());
